<?php

return [
    'lup_default' => [
        'key' => 'lup_default',
        'name' => 'setting_lup_default',
        'description' => 'setting_lup_default_desc',
        'value' => '',
        'xtype' => 'textfield',
        'namespace' => 'loginup',
        'area' => 'lup',
    ],
    'lup_accesstype' => [
        'key' => 'lup_accesstype',
        'name' => 'setting_lup_accesstype',
        'description' => 'setting_lup_accesstype_desc',
        'value' => 'jpg, jpeg, png, gif',
        'xtype' => 'textfield',
        'namespace' => 'loginup',
        'area' => 'lup',
    ],
    'lup_width' => [
        'key' => 'lup_width',
        'name' => 'setting_lup_width',
        'description' => 'setting_lup_width_desc',
        'value' => '300',
        'xtype' => 'numberfield',
        'namespace' => 'loginup',
        'area' => 'lup',
    ],
    'lup_height' => [
        'key' => 'lup_height',
        'name' => 'setting_lup_height',
        'description' => 'setting_lup_height_desc',
        'value' => '300',
        'xtype' => 'numberfield',
        'namespace' => 'loginup',
        'area' => 'lup',
    ],
    'lup_quality' => [
        'key' => 'lup_quality',
        'name' => 'setting_lup_quality',
        'description' => 'setting_lup_quality_desc',
        'value' => '100',
        'xtype' => 'numberfield',
        'namespace' => 'loginup',
        'area' => 'lup',
    ],
    'lup_zc' => [
        'key' => 'lup_zc',
        'name' => 'setting_lup_zc',
        'description' => 'setting_lup_zc_desc',
        'value' => '1',
        'xtype' => 'numberfield',
        'namespace' => 'loginup',
        'area' => 'lup',
    ],
    'lup_customize_grid' => [
        'key' => 'lup_customize_grid',
        'name' => 'setting_lup_customize_grid',
        'description' => 'setting_lup_customize_grid_desc',
        'value' => '1',
        'xtype' => 'combo-boolean',
        'namespace' => 'loginup',
        'area' => 'lup',
    ],
    'lup_customize_profile' => [
        'key' => 'lup_customize_profile',
        'name' => 'setting_lup_customize_profile',
        'description' => 'setting_lup_customize_profile_desc',
        'value' => '1',
        'xtype' => 'combo-boolean',
        'namespace' => 'loginup',
        'area' => 'lup',
    ],
    'lup_directory' => [
        'key' => 'lup_directory',
        'name' => 'setting_lup_directory',
        'description' => 'setting_lup_directory_desc',
        'value' => 'user_photos',
        'xtype' => 'textfield',
        'namespace' => 'loginup',
        'area' => 'lup',
    ],
];
