<?php

return [
    'LUP_Login' => [
        'file' => 'lup_login',
        'description' => 'Login snippet for LoginUp',
        'properties' => [
            'actionKey' => [
                'desc' => 'prop_login.actionkey_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'service',
                'lexicon' => 'login:properties',
            ],
            'loginKey' => [
                'desc' => 'prop_login.loginkey_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'login',
                'lexicon' => 'login:properties',
            ],
            'logoutKey' => [
                'desc' => 'prop_login.logoutkey_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'logout',
                'lexicon' => 'login:properties',
            ],
            'tplType' => [
                'desc' => 'prop_login.tpltype_desc',
                'type' => 'list',
                'options' => [
                    ['name' => 'opt_register.chunk', 'value' => 'modChunk'],
                    ['name' => 'opt_register.file', 'value' => 'file'],
                    ['name' => 'opt_register.inline', 'value' => 'inline'],
                    ['name' => 'opt_register.embedded', 'value' => 'embedded'],
                ],
                'value' => 'modChunk',
                'lexicon' => 'login:properties',
            ],
            'loginTpl' => [
                'desc' => 'prop_login.logintpl_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'lgnLoginTpl',
                'lexicon' => 'login:properties',
            ],
            'logoutTpl' => [
                'desc' => 'prop_login.logouttpl_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'lgnLogoutTpl',
                'lexicon' => 'login:properties',
            ],
            'preHooks' => [
                'desc' => 'prop_login.prehooks_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => false,
                'lexicon' => 'login:properties',
            ],
            'postHooks' => [
                'desc' => 'prop_login.posthooks_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => false,
                'lexicon' => 'login:properties',
            ],
            'errTpl' => [
                'desc' => 'prop_login.errtpl_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'lgnErrTpl',
                'lexicon' => 'login:properties',
            ],
            'errTplType' => [
                'desc' => 'prop_login.errtpltype_desc',
                'type' => 'list',
                'options' => [
                    ['name' => 'opt_register.chunk', 'value' => 'modChunk'],
                    ['name' => 'opt_register.file', 'value' => 'file'],
                    ['name' => 'opt_register.inline', 'value' => 'inline'],
                    ['name' => 'opt_register.embedded', 'value' => 'embedded'],
                ],
                'value' => 'modChunk',
                'lexicon' => 'login:properties',
            ],
            'loginResourceId' => [
                'desc' => 'prop_login.loginresourceid_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 0,
                'lexicon' => 'login:properties',
            ],
            'loginResourceParams' => [
                'desc' => 'prop_login.loginresourceparams_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'logoutResourceId' => [
                'desc' => 'prop_login.logoutresourceid_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 0,
                'lexicon' => 'login:properties',
            ],
            'logoutResourceParams' => [
                'desc' => 'prop_login.logoutresourceparams_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'loginMsg' => [
                'desc' => 'prop_login.loginmsg_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'logoutMsg' => [
                'desc' => 'prop_login.logoutmsg_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'redirectToPrior' => [
                'desc' => 'prop_login.redirecttoprior_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => false,
                'lexicon' => 'login:properties',
            ],
            'redirectToOnFailedAuth' => [
                'desc' => 'prop_login.redirecttoonfailedauth_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'rememberMeKey' => [
                'desc' => 'prop_login.remembermekey_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'rememberme',
                'lexicon' => 'login:properties',
            ],
            'contexts' => [
                'desc' => 'prop_login.contexts_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'toPlaceholder' => [
                'desc' => 'prop_login.toplaceholder_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            /* recaptcha hook */
            'recaptchaTheme' => [
                'desc' => 'prop_register.recaptchatheme_desc',
                'type' => 'list',
                'options' => [
                    ['text' => 'opt_register.red', 'value' => 'red'],
                    ['text' => 'opt_register.white', 'value' => 'white'],
                    ['text' => 'opt_register.clean', 'value' => 'clean'],
                    ['text' => 'opt_register.blackglass', 'value' => 'blackglass'],
                ],
                'value' => 'clean',
                'lexicon' => 'login:properties',
            ],
            'jsonResponse' => [
                'desc' => 'setting_lup_jsonresponse_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'loginup:default',
            ],
            'logoutAntiJson' => [
                'desc' => 'setting_lup_logoutantijson_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'loginup:default',
            ],
        ]
    ],
    'LUP_ForgotPassword' => [
        'file' => 'lup_forgotpassword',
        'description' => 'ForgotPassword snippet for LoginUp',
        'properties' => [
            'emailTpl' => [
                'desc' => 'prop_forgotpassword.emailtpl_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'lgnForgotPassEmail',
                'lexicon' => 'login:properties',
            ],
            'emailTplAlt' => [
                'desc' => 'prop_forgotpassword.emailtplalt_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'emailTplType' => [
                'desc' => 'prop_forgotpassword.emailtpltype_desc',
                'type' => 'list',
                'options' => [
                    ['name' => 'opt_register.chunk', 'value' => 'modChunk'],
                    ['name' => 'opt_register.file', 'value' => 'file'],
                    ['name' => 'opt_register.inline', 'value' => 'inline'],
                    ['name' => 'opt_register.embedded', 'value' => 'embedded'],
                ],
                'value' => 'modChunk',
                'lexicon' => 'login:properties',
            ],
            'sentTpl' => [
                'desc' => 'prop_forgotpassword.senttpl_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'lgnForgotPassSentTpl',
                'lexicon' => 'login:properties',
            ],
            'sentTplType' => [
                'desc' => 'prop_forgotpassword.senttpltype_desc',
                'type' => 'list',
                'options' => [
                    ['name' => 'opt_register.chunk', 'value' => 'modChunk'],
                    ['name' => 'opt_register.file', 'value' => 'file'],
                    ['name' => 'opt_register.inline', 'value' => 'inline'],
                    ['name' => 'opt_register.embedded', 'value' => 'embedded'],
                ],
                'value' => 'modChunk',
                'lexicon' => 'login:properties',
            ],
            'tpl' => [
                'desc' => 'prop_forgotpassword.tpl_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'lgnForgotPassTpl',
                'lexicon' => 'login:properties',
            ],
            'tplType' => [
                'desc' => 'prop_forgotpassword.tpltype_desc',
                'type' => 'list',
                'options' => [
                    ['name' => 'opt_register.chunk', 'value' => 'modChunk'],
                    ['name' => 'opt_register.file', 'value' => 'file'],
                    ['name' => 'opt_register.inline', 'value' => 'inline'],
                    ['name' => 'opt_register.embedded', 'value' => 'embedded'],
                ],
                'value' => 'modChunk',
                'lexicon' => 'login:properties',
            ],
            'errTpl' => [
                'desc' => 'prop_forgotpassword.errtpl_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'lgnErrTpl',
                'lexicon' => 'login:properties',
            ],
            'errTplType' => [
                'desc' => 'prop_forgotpassword.errtpltype_desc',
                'type' => 'list',
                'options' => [
                    ['name' => 'opt_register.chunk', 'value' => 'modChunk'],
                    ['name' => 'opt_register.file', 'value' => 'file'],
                    ['name' => 'opt_register.inline', 'value' => 'inline'],
                    ['name' => 'opt_register.embedded', 'value' => 'embedded'],
                ],
                'value' => 'modChunk',
                'lexicon' => 'login:properties',
            ],
            'emailSubject' => [
                'desc' => 'prop_forgotpassword.emailsubject_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'resetResourceId' => [
                'desc' => 'prop_forgotpassword.resetresourceid_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 1,
                'lexicon' => 'login:properties',
            ],
            'redirectTo' => [
                'desc' => 'prop_forgotpassword.redirectto_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'redirectParams' => [
                'desc' => 'prop_forgotpassword.redirectparams_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'jsonResponse' => [
                'desc' => 'setting_lup_jsonresponse_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'loginup:default',
            ],
        ]
    ],
    'LUP_ChangePassword' => [
        'file' => 'lup_changepassword',
        'description' => 'ChangePassword snippet for LoginUp',
        'properties' => [
            'submitVar' => [
                'desc' => 'prop_changepassword.submitvar_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'logcp-submit',
                'lexicon' => 'login:properties',
            ],
            'fieldOldPassword' => [
                'desc' => 'prop_changepassword.fieldoldpassword_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'password_old',
                'lexicon' => 'login:properties',
            ],
            'fieldNewPassword' => [
                'desc' => 'prop_changepassword.fieldnewpassword_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'password_new',
                'lexicon' => 'login:properties',
            ],
            'fieldConfirmNewPassword' => [
                'desc' => 'prop_changepassword.fieldconfirmnewpassword_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'password_new_confirm',
                'lexicon' => 'login:properties',
            ],
            'preHooks' => [
                'desc' => 'prop_changepassword.prehooks_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'postHooks' => [
                'desc' => 'prop_changepassword.posthooks_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'redirectToLogin' => [
                'desc' => 'prop_changepassword.redirecttologin_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'login:properties',
            ],
            'reloadOnSuccess' => [
                'desc' => 'prop_changepassword.reloadonsuccess_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => false,
                'lexicon' => 'login:properties',
            ],
            'successMessage' => [
                'desc' => 'prop_changepassword.successmessage_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'placeholderPrefix' => [
                'desc' => 'prop_changepassword.placeholderprefix_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'logcp.',
                'lexicon' => 'login:properties',
            ],
            'jsonResponse' => [
                'desc' => 'setting_lup_jsonresponse_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'loginup:default',
            ],
        ]
    ],
    'LUP_Register' => [
        'file' => 'lup_register',
        'description' => 'Register snippet for LoginUp',
        'properties' => [
            'submitVar' => [
                'desc' => 'prop_register.submitvar_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'usergroups' => [
                'desc' => 'prop_register.usergroups_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'usergroupsField' => [
                'desc' => 'prop_register.usergroupsfield_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'submittedResourceId' => [
                'desc' => 'prop_register.submittedresourceid_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'usernameField' => [
                'desc' => 'prop_register.usernamefield_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'username',
                'lexicon' => 'login:properties',
            ],
            'passwordField' => [
                'desc' => 'prop_register.passwordfield_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'password',
                'lexicon' => 'login:properties',
            ],
            'validatePassword' => [
                'desc' => 'prop_register.validatepassword_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'login:properties',
            ],
            'generatePassword' => [
                'desc' => 'prop_register.generatepassword_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => false,
                'lexicon' => 'login:properties',
            ],
            'trimPassword' => [
                'desc' => 'prop_register.trimpassword_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'login:properties',
            ],
            'ensurePasswordStrength' => [
                'desc' => 'prop_register.ensurePasswordStrength_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => false,
                'lexicon' => 'login:properties',
            ],
            'passwordWordSeparator' => [
                'desc' => 'prop_register.passwordWordSeparator_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => ' ',
                'lexicon' => 'login:properties',
            ],
            'minimumStrongPasswordWordCount' => [
                'desc' => 'prop_register.minimumStrongPasswordWordCount_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 3,
                'lexicon' => 'login:properties',
            ],
            'maximumPossibleStrongerPasswords' => [
                'desc' => 'prop_register.maximumPossibleStrongerPasswords_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 25,
                'lexicon' => 'login:properties',
            ],
            'ensurePasswordStrengthSuggestions' => [
                'desc' => 'prop_register.ensurePasswordStrengthSuggestions_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => 5,
                'lexicon' => 'login:properties',
            ],
            'allowedFields' => [
                'desc' => 'prop_register.allowedfields_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'emailField' => [
                'desc' => 'prop_register.emailfield_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'email',
                'lexicon' => 'login:properties',
            ],
            'successMsg' => [
                'desc' => 'prop_register.successmsg_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'persistParams' => [
                'desc' => 'prop_register.persistparams_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'preHooks' => [
                'desc' => 'prop_register.prehooks_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'postHooks' => [
                'desc' => 'prop_register.posthooks_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'useExtended' => [
                'desc' => 'prop_register.useextended_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'login:properties',
            ],
            'excludeExtended' => [
                'desc' => 'prop_register.excludeextended_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'activation' => [
                'desc' => 'prop_register.activation_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'login:properties',
            ],
            'activationttl' => [
                'desc' => 'prop_register.activationttl_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '180',
                'lexicon' => 'login:properties',
            ],
            'activationResourceId' => [
                'desc' => 'prop_register.activationresourceid_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 1,
                'lexicon' => 'login:properties',
            ],
            'activationEmail' => [
                'desc' => 'prop_register.activationemail_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'activationEmailSubject' => [
                'desc' => 'prop_register.activationemailsubject_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'activationEmailTplType' => [
                'desc' => 'prop_register.activationemailtpltype_desc',
                'type' => 'list',
                'options' => [
                    ['name' => 'opt_register.chunk', 'value' => 'modChunk'],
                    ['name' => 'opt_register.file', 'value' => 'file'],
                    ['name' => 'opt_register.inline', 'value' => 'inline'],
                    ['name' => 'opt_register.embedded', 'value' => 'embedded'],
                ],
                'value' => 'modChunk',
                'lexicon' => 'login:properties',
            ],
            'activationEmailTpl' => [
                'desc' => 'prop_register.activationemailtpl_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'lgnActivateEmailTpl',
                'lexicon' => 'login:properties',
            ],
            'activationEmailTplAlt' => [
                'desc' => 'prop_register.activationemailtplalt_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'moderatedResourceId' => [
                'desc' => 'prop_register.moderatedresourceid_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'removeExpiredRegistrations' => [
                'desc' => 'prop_register.removeexpiredregistrations_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'login:properties',
            ],
            'placeholderPrefix' => [
                'desc' => 'prop_register.placeholderprefix_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            /* recaptcha hook */
            'recaptchaTheme' => [
                'desc' => 'prop_register.recaptchatheme_desc',
                'type' => 'list',
                'options' => [
                    ['text' => 'opt_register.red', 'value' => 'red'],
                    ['text' => 'opt_register.white', 'value' => 'white'],
                    ['text' => 'opt_register.clean', 'value' => 'clean'],
                    ['text' => 'opt_register.blackglass', 'value' => 'blackglass'],
                ],
                'value' => 'clean',
                'lexicon' => 'login:properties',
            ],
            /* math hook */
            'mathMinRange' => [
                'desc' => 'prop_register.mathminrange_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 10,
                'lexicon' => 'login:properties',
            ],
            'mathMaxRange' => [
                'desc' => 'prop_register.mathmaxrange_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 100,
                'lexicon' => 'login:properties',
            ],
            'mathField' => [
                'desc' => 'prop_register.mathfield_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'math',
                'lexicon' => 'login:properties',
            ],
            'mathOp1Field' => [
                'desc' => 'prop_register.mathop1field_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'op1',
                'lexicon' => 'login:properties',
            ],
            'mathOp2Field' => [
                'desc' => 'prop_register.mathop2field_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'op2',
                'lexicon' => 'login:properties',
            ],
            'mathOperatorField' => [
                'desc' => 'prop_register.mathoperatorfield_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'operator',
                'lexicon' => 'login:properties',
            ],
            'jsonResponse' => [
                'desc' => 'setting_lup_jsonresponse_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'loginup:default',
            ],
        ]
    ],
    'LUP_UpdateProfile' => [
        'file' => 'lup_updateprofile',
        'description' => 'UpdateProfile snippet for LoginUp',
        'properties' => [
            'submitVar' => [
                'desc' => 'prop_updateprofile.submitvar_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'user' => [
                'desc' => 'prop_updateprofile.user_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'redirectToLogin' => [
                'desc' => 'prop_updateprofile.redirecttologin_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'login:properties',
            ],
            'reloadOnSuccess' => [
                'desc' => 'prop_updateprofile.reloadonsuccess_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => false,
                'lexicon' => 'login:properties',
            ],
            'syncUsername' => [
                'desc' => 'prop_updateprofile.syncusername_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'emailField' => [
                'desc' => 'prop_updateprofile.emailfield_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => 'email',
                'lexicon' => 'login:properties',
            ],
            'useExtended' => [
                'desc' => 'prop_updateprofile.useextended_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'login:properties',
            ],
            'excludeExtended' => [
                'desc' => 'prop_updateprofile.excludeextended_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'allowedFields' => [
                'desc' => 'prop_updateprofile.allowedfields_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'allowedExtendedFields' => [
                'desc' => 'prop_updateprofile.allowedextendedfields_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'preHooks' => [
                'desc' => 'prop_updateprofile.prehooks_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'postHooks' => [
                'desc' => 'prop_updateprofile.posthooks_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'placeholderPrefix' => [
                'desc' => 'prop_updateprofile.placeholderprefix_desc',
                'type' => 'textfield',
                'options' => '',
                'value' => '',
                'lexicon' => 'login:properties',
            ],
            'jsonResponse' => [
                'desc' => 'setting_lup_jsonresponse_desc',
                'type' => 'combo-boolean',
                'options' => '',
                'value' => true,
                'lexicon' => 'loginup:default',
            ],
        ],
    ],
    'LUP_ConfirmRegister' => [
        'file' => 'lup_confirmregister',
        'description' => '',
        'properties' => [
            "redirectTo" => [
                "name" => "redirectTo",
                "desc" => "prop_confirmregister.redirectto_desc",
                "type" => "textfield",
                "options" => "",
                "value" => "",
                "lexicon" => "login:properties"
            ],
            "redirectParams" => [
                "name" => "redirectParams",
                "desc" => "prop_confirmregister.redirectparams_desc",
                "type" => "textfield",
                "options" => "",
                "value" => "",
                "lexicon" => "login:properties"
            ],
            "redirectUnsetDefaultParams" => [
                "name" => "redirectUnsetDefaultParams",
                "desc" => "prop_confirmregister.redirectUnsetDefaultParam_desc",
                "type" => "combo-boolean",
                "options" => "",
                "value" => false,
                "lexicon" => "login:properties"
            ],
            "authenticate" => [
                "name" => "authenticate",
                "desc" => "prop_confirmregister.authenticate_desc",
                "type" => "combo-boolean",
                "options" => "",
                "value" => true,
                "lexicon" => "login:properties"
            ],
            "authenticateContexts" => [
                "name" => "authenticateContexts",
                "desc" => "prop_confirmregister.authenticatecontexts_desc",
                "type" => "textfield",
                "options" => "",
                "value" => "",
                "lexicon" => "login:properties"
            ],
            "errorPage" => [
                "name" => "errorPage",
                "desc" => "prop_confirmregister.errorpage_desc",
                "type" => "textfield",
                "options" => "",
                "value" => "",
                "lexicon" => "login:properties"
            ],
            "activePage" => [
                "name" => "activePage",
                "desc" => "prop_confirmregister.activepage_desc",
                "type" => "textfield",
                "options" => "",
                "value" => "",
                "lexicon" => "login:properties"
            ]
        ],
    ],
    'LUP_pre_photo' => [
        'file' => 'lup_pre_photo',
        'description' => 'LoginUp pre-hook to upload photo',
    ],
    'LUP_pre_username' => [
        'file' => 'lup_pre_username',
        'description' => 'LoginUp pre-hook to change username',
    ],
    'LUP_post_photo' => [
        'file' => 'lup_post_photo',
        'description' => 'LoginUp post-hook to precheck photo',
    ],
    'LUP' => [
        'file' => 'lup',
        'description' => 'LoginUp default snippet',
        'properties' => [
            'selector' => [
                'type' => 'textfield',
                'value' => '.lup_photo_remove_btn',
            ],
            'frontend_js' => [
                'type' => 'textfield',
                'value' => '[[+assetsUrl]]js/web/default.js',
            ],
            'lexicons' => [
                'type' => 'textfield',
                'value' => '',
            ]
        ],
    ],
];

